name: Space-Track Daily Ingest

on:
  schedule:
    - cron: "15 07 * * *"   # 07:15 UTC daily (~12:15 AM PT)
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      PYTHONUNBUFFERED: "1"
      GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
      GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
      EXPORT_PREFIX: "space-track/"
      EXPORT_HOURS: "24"
      # FETCH_MODE: "DELTA"  # uncomment to switch to delta pulls
      # SINCE_ISO: "2025-08-22T00:00:00" # optional override

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests psycopg2-binary google-cloud-storage

      # —— Auth to GCP for Cloud Storage upload ——
      - name: Configure gcloud credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      # —— Start Cloud SQL Auth Proxy (Postgres) ——
      - name: Download & start Cloud SQL Auth Proxy
        run: |
          curl -sLo cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.10.1/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          ./cloud-sql-proxy --private-ip "${{ secrets.INSTANCE_CONNECTION_NAME }}" --port 5432 &
          sleep 3
        shell: bash

      - name: Set DB env
        run: |
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
        shell: bash

      - name: Run ingestion
        env:
          ST_USERNAME: ${{ secrets.ST_USERNAME }}
          ST_PASSWORD: ${{ secrets.ST_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASSWORD }}
        run: |
          python backend/datapipe/spacetrack_data_fetcher.py
