name: Weekly minor_planets.json Update

on:
  workflow_dispatch:
  schedule:
    # Runs at 08:00 UTC every Sunday
    - cron: '0 8 * * 0'

jobs:
  update-minor-planet-data:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests
      
      - name: Run MPCORB Parser
        run: python ./scripts/update_minor_planets.py

      - name: Commit and Push if Changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          # Add both the data file and the new report file
          git add public/data/json/minor_planets.json scripts/reports/update_minor_planets_report.txt
          git diff --staged --quiet || git commit -m "Automated: Weekly minor planet data and report update"
          git push || echo "No changes to push."
